name: Publish

permissions:
  contents: write

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm & ni
        run: npm install -g pnpm @antfu/ni

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: nci

      - name: Prepare
        run: nr dev:prepare

      - name: Prepack
        run: nr prepack

      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
